### PR TITLE
Making the Database JSON based rather then mySQL

### PR DESCRIPTION
**Pull request by ducksquaddd**
Making the Database just JSON makes it easier for any user who wishes to download and use this repo. Because who really wants to go through the hassle of setting up MySql db just for botting roblox accounts.

Making it JSON based means the user has no problem with setting up a db because the program does it itself.

I have used the same naming conventions with functions and what not so everything still works the same just two lines in index.js change. 
if (!(await DBUtil.connect())) return; > Is gone 
await DBUtil.setupDB('database.json') > setupDB now takes a param to init the db

Edit: You also dont have to worry about corruptions because it writes the file atomically. Meaning it cant be interrupted also meaning no corruptions 

Edit two: The package for editing the data is made by me :) If you want to check for malicious code you can see the code here: https://github.com/Vedux-Development/VeduDB

### CODE REVIEW

**Comment by Arcxdd** [comment]
I'd do this on another branch, just because mysql can be deployed in the cloud and opens up more possibilities for this generator, like a full frontend and backend stack.

**Comment by WaltDisneyWorld** [comment]
I disagree

**Comment by WaltDisneyWorld** [comment]
If anything, I would move to mongo for a better user experience.

**Comment by Arcxdd** [comment]
And setting up mongo is easier than mysql?

**Comment by Arcxdd** [comment]
Right..

**Comment by WaltDisneyWorld** [comment]
> And setting up mongo is easier than mysql?

Some people say so. Your choice..

**Comment by ducksquaddd** [comment]
> I'd do this on another branch, just because mysql can be deployed in the cloud and opens up more possibilities for this generator, like a full frontend and backend stack.

Launching a database to the cloud for a simple roblox account gen lol, Just personally if i really wanted to bot a bunch of roblox accounts I would just go to another open source project. Setting up a mySql database for something as simple as this seems useless and over the top

**Comment by ducksquaddd** [comment]
> I'd do this on another branch, just because mysql can be deployed in the cloud and opens up more possibilities for this generator, like a full frontend and backend stack.

I don't see why making the database JSON gets rid of possibilities of having a full stack. Just making something as simple as this makes sense to have it as a simple data format

**Comment by Arcxdd** [comment]
I meant if someone elses uses this repo as their own and launches their own service, not us.

**Comment by ducksquaddd** [comment]
> > I don't see why making the database JSON gets rid of possibilities of having a full stack. Just making something as simple as this makes sense to have it as a simple data format.
> 
> > "Generally using separate boxes for MySQL and Web Servers is rather good practice. It is more secure – Compromising your web server does not directly give access to your database, even though most applications have enough database access permissions to be allow intruder to trash/dump data."
> 
> Look at it this way, if someone wanted to deploy this on a larger scale, wouldn't they want more security?
> 
> I'm talking full REST API with frontend and a domain. Commercial purposes with people buying lists of ROBLOX accounts.
> 
> Sure, they would probably write their own version of this, but still. I'll let the repository owner review and think.

Also people buying Roblox accounts from y'all 😬great way to receive a ceise and desist and a law suit from Roblox lol

**Comment by ducksquaddd** [comment]
> I meant if someone elses uses this repo as their own and launches their own service, not us.

If they want to launch as a full fledge service then they should be able to modify the code themselves. But making it JSON will make it easier for everyday users

**Comment by Arcxdd** [comment]
> > I meant if someone elses uses this repo as their own and launches their own service, not us.
> 
> If they want to launch as a full fledge service then they should be able to modify the code themselves. But making it JSON will make it easier for everyday users

Right.

**Comment by Arcxdd** [comment]
Ignore the C&D and get sued for a few million

**Comment by jluims** [comment]
> Ignore the C&D and get sued for a few million

Maybe if I get sued for enough, I'll cause an overflow error and become rich 😭

**Pull request merged**
