### PR TITLE
Add multiple DB support

### PR DESCRIPTION
**Pull request by jluims**
This adds support for both mysql and vedu (json).
It can be configured by the DB_TYPE field in .env

### CODE REVIEW

**Comment by Arcxdd** [comment]
I'm trying to sleep and you dump this on me 😭

**Comment by jluims** [comment]
Sorry 😭 what's your timezone?

**Comment by Arcxdd** [comment]
GMT+2

**Comment by Arcxdd** [comment]
Looks good to me

**Pull request merged**
