### PR TITLE
Reformed

### PR DESCRIPTION
**Pull request by Arcxdd**

### CODE REVIEW

**Comment by jluims** [comment]
I think you have the ability to merge this yourself, not sure tho.

**Comment by Arcxdd** [comment]
I don't think I do, won't let me.

**Comment by Arcxdd** [comment]
And vscode says I can't merge due to insufficient permissions.

**Comment by jluims** [comment]
I invited you yesterday, did you get an email?

**Comment by jluims** [comment]
By the way, doesn't using "=== null" make it always false? It caused me some issues yesterday

**Comment by jluims** [comment]
I think it may not be returning null somewhere I'll check it out later

**Comment by Arcxdd** [comment]
also, you should probably use `(!fieldData)` instead of checking if its null, since it does the same

**Pull request merged**
