### PR TITLE
Fixed getting a random account

### PR DESCRIPTION
**Pull request by Arcxdd**
sqlMessage: "Table 'accounts.Accounts' doesn't exist"

### CODE REVIEW

**Comment by Arcxdd** [comment]
I changed the db to accounts instead of rbxgen locally, sorry if you got confused, my bad.

**Comment by Arcxdd** [comment]
Still accept the cool bug fix 😎😎

**Comment by jluims** [comment]
bruh 😭 at this point i'll just go over the whole thing

**Comment by Arcxdd** [comment]
😭😭

**Pull request merged**
